---
name: docs
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/**"
      - "docs/**"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      - name: build
        uses: shalzz/zola-deploy-action@186b5039430ab38781dde8feaf0861bcc017413f  # v0.16.1-1
        env:
          BUILD_DIR: docs
          BUILD_ONLY: true
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847  # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
